version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost "]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - masato

  grpc-server:
    build: 
      context: .
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - "${GRPC_SERVER_PORT}:9000" # Expose the gRPC server on port 9000
    container_name: grpc-server-container
    networks:
      - masato

  api-gateway:
    build: 
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    ports:
      - "8080:8080" # Expose the API gateway on port 8080
    container_name: gateway-container
    depends_on:
      mysql:
        condition: service_healthy
      grpc-server:
        condition: service_started
    environment:
      - GRPC_SERVER_HOST=grpc-server:9000
    networks:
      - masato

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_volume:
  mysql_volume:

networks:
  masato: {}