version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
  grpc-server:
    build: 
      context: .
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - "9000:9000" # Expose the gRPC server on port 9000
    container_name: grpc-server-container
    networks:
      - masato

  api-gateway:
    build: 
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    ports:
      - "8080:8080" # Expose the API gateway on port 8080
    container_name: gateway-container
    depends_on:
      - grpc-server
    environment:
      - GRPC_SERVER_HOST=grpc-server:9000
    networks:
      - masato

volumes:
  mongo_volume:
  mysql_volume:

networks:
  masato: {}