version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: regdealer
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3333:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost "]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - masato

  grpc-server:
    build: 
      context: .
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - "9999:9000" # Expose the gRPC server on port 9000
    container_name: grpc-server-container
    networks:
      - masato

  api-gateway:
    build: 
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    ports:
      - "8080:8080" # Expose the API gateway on port 8080
    container_name: gateway-container
    depends_on:
      mysql:
        condition: service_healthy
      grpc-server:
        condition: service_started
    environment:
      - GRPC_SERVER_HOST=grpc-server:9000
      - SQL_DB_DSN = root:root@tcp(mysql:3306)/regdealer
    networks:
      - masato

volumes:
  mongo_volume:
  mysql_volume:

networks:
  masato: {}